export const ingestionApiDocs = {
  planRoute: {
    summary: 'Solicitar planificación de rutas (Asíncrono)',
    description: [
      'Este endpoint permite solicitar la planificación de rutas de distribución a partir de un conjunto de entregas y camiones disponibles.',
      '',
      'El procesamiento de la solicitud se realiza de forma asíncrona.',
      '',
      '### Webhook Callback (Notificación de finalización)',
      'Una vez que el motor matemático finalice el cálculo (o falle), el servicio `DispatchService` enviará una solicitud HTTP al endpoint configurado.',
      '',
      '```http',
      'POST <callbackUrl>',
      '```',
      '',
      'La URL `callbackUrl` debe haber sido previamente configurada por el cliente.',
      '',
      '### Seguridad (Verificación de Firma)',
      'Para garantizar la autenticidad de la notificación, cada webhook incluye una firma criptográfica en los encabezados HTTP.',
      '',
      '**Header utilizado:**',
      '`X-Signature`',
      '',
      '**Formato de la firma:**',
      '`sha256=<hash_hexadecimal>`',
      '',
      'La firma se generará utilizando el algoritmo `HMAC SHA-256` con la clave secreta `clientSecret` y el cuerpo crudo de la petición `(raw body)`.',
      '',
      '### Codificación',
      'El payload debe procesarse utilizando codificación **UTF-8** para evitar inconsistencias en la verificación de la firma.',
      '',
      '### Prevención de Timing Attacks',
      'Se recomienda utilizar funciones de comparación en tiempo constante.',
      '',
      '**Ejemplo en Java:**',
      '```java',
      'MessageDigest.isEqual(expectedSignature, receivedSignature);',
      '```',
      '',
      '**Ejemplo en Node.js:**',
      '```javascript',
      'crypto.timingSafeEqual(expectedSignature, receivedSignature);',
      '```',
      '',
      'Evitar comparaciones directas con `==` o `===`.',
      '',
      '### Payload de Ejemplo (Éxito)',
      'Se envía cuando el cálculo finaliza correctamente (`event_type: "routing.completed"`).',
      '```json',
      '{',
      '  "event_id": "evt_7b92a18c-4e5d-4a11-b2c3-9f8d7e6c5b4a",',
      '  "event_type": "routing.completed",',
      '  "request_id": "123e4567-e89b-12d3-a456-425614134023",',
      '  "timestamp": "2026-03-18T08:05:00.000Z",',
      '  "data": {',
      '    "routes": [',
      '      {',
      '        "truckId": "CAMION-CHICO",',
      '        "assignedRouteId": "ROUTE-74EA598C",',
      '        "estimatedStartTime": "2026-03-18T08:00:00.000Z",',
      '        "estimatedEndTime": "2026-03-18T08:47:00.000Z",',
      '        "totalDistanceKm": 8.27,',
      '        "totalDurationMins": 47,',
      '        "stops": [',
      '          {',
      '            "stopNumber": 1,',
      '            "deliveryCode": "ENT-001",',
      '            "estimatedArrivalTime": "2026-03-18T08:04:00.000Z"',
      '          }',
      '        ]',
      '      }',
      '    ],',
      '    "unassignedDeliveries": []',
      '  }',
      '}',
      '```',
      '',
      '### Payload de Ejemplo (Fallo)',
      'Se envía cuando el motor matemático falla o los datos son irruteables (`event_type: "routing.failed"`).',
      '```json',
      '{',
      '  "event_id": "evt_8c32a18c-4e5d-4a11-b2c3-9f8d7e6c5b99",',
      '  "event_type": "routing.failed",',
      '  "request_id": "123e4567-e89b-12d3-a456-425614134023",',
      '  "timestamp": "2026-03-18T08:05:00.000Z",',
      '  "error": {',
      '    "code": "UNPROCESSABLE_ROUTE",',
      '    "message": "Mensaje detallado del error matemático."',
      '  }',
      '}',
      '```',
      '',
      '### Diccionario de Datos',
      '',
      '| Campo | Tipo | Descripción |',
      '| --- | --- | --- |',
      '| `event_id` | `String` | `Identificador único del evento` |',
      '| `event_type` | `String` | `Tipo de evento (routing.completed o routing.failed)` |',
      '| `request_id` | `String` | `ID de la solicitud original` |',
      '| `timestamp` | `String` | `Fecha en formato ISO 8601` |',
      '| `data.routes` | `Array` | `Rutas asignadas (Solo en éxito)` |',
      '| `truckId` | `String` | `Identificador del camión` |',
      '| `assignedRouteId` | `String` | `Identificador de la ruta` |',
      '| `estimatedStartTime` | `String` | `Hora estimada de salida` |',
      '| `estimatedEndTime` | `String` | `Hora estimada de finalización` |',
      '| `totalDistanceKm` | `Float` | `Distancia total en kilómetros` |',
      '| `totalDurationMins` | `Integer` | `Duración total en minutos` |',
      '| `stops` | `Array` | `Paradas de la ruta` |',
      '| `data.unassignedDeliveries` | `Array` | `Entregas no asignadas` |',
      '| `error` | `Object` | `Objeto de error (Solo en fallo)` |',
      '| `error.code` | `String` | `Código interno del error` |',
      '| `error.message` | `String` | `Explicación técnica del rechazo` |',
      '',
      '### Expectativas de Respuesta',
      'El servidor que recibe el webhook debe responder con:',
      '```http',
      'HTTP 200 OK',
      '```',
      'La respuesta debe enviarse en menos de **5 segundos** para confirmar la recepción del evento.',
    ].join('\n'),
    responses: {
      accepted: 'Solicitud aceptada para procesamiento',
      badRequest: 'Datos de solicitud inválidos',
      unauthorized: 'API key inválida o ausente',
    },
  },

  getPlannedRoute: {
    summary: 'Consultar el estado y resultado de una planificación (Polling)',
    paramDescription: 'ID de la solicitud (requestId)',
    responses: {
      ok: 'Estado actual de la solicitud. Si es COMPLETED incluye las rutas. Si es FAILED incluye el motivo del error.',
      notFound: 'Solicitud no encontrada o no pertenece a tu grupo',
      unauthorized: 'API key inválida o ausente',
    },
  },
};
